import React from "react";
import Link from "next/link";

export const metadata = {
  title: "About ",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div>
      <h1>This is About page</h1>
      <Link href="/">Go back to home</Link>
    </div>
  );
}
