import React from "react";
import Link from "next/link";

export const metadata = {
  title: "Career ",
  description: "Generated by create next app",
};

export default function Career() {
  return (
    <div>
      <h1>Why join us</h1>
      <Link href="/">Go back to home</Link>
    </div>
  );
}
